/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import DBConnect.DataBase;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import javax.swing.JOptionPane;
import java.sql.*;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.PreparedStatement;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import java.sql.Date;
import java.text.ParseException;
import java.text.SimpleDateFormat;




/**
 *
 * @author nara
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        tampilkanDataPenyewa();
        
        PanelMainMenu.setVisible(true);
        PanelPenyewaBaru.setVisible(true);
        PanelPekerja.setVisible(true);
        PanelPelajar.setVisible(true);
        PanelEditPenyewa.setVisible(false);

        CBStatusPenyewa.addActionListener((ActionEvent e) -> {
            String selectedStatus = (String) CBStatusPenyewa.getSelectedItem();
            if ("Pekerja".equals(selectedStatus)) {
                TFNamaPerusahaan.setEditable(true);
                TFJabatan.setEditable(true);
                
                TFNamaPerusahaan.setText("");
                TFJabatan.setText("");
                
                TFNamaSekolah.setText("-");
                TFNamaSekolah.setEditable(false);
                
                TFNamaJurusan.setText("-");
                TFNamaJurusan.setEditable(false);
                
            } else if ("Pelajar".equals(selectedStatus)) {
                TFNamaSekolah.setEditable(true);
                TFNamaJurusan.setEditable(true);
                
                TFNamaSekolah.setText("");
                TFNamaJurusan.setText("");
                
                TFNamaPerusahaan.setText("-");
                TFNamaPerusahaan.setEditable(false);
                
                TFJabatan.setText("-");
                TFJabatan.setEditable(false);
                
                
                
            }else {
                TFNamaSekolah.setText("");
                TFNamaJurusan.setText("");
                TFNamaPerusahaan.setText("");
                TFJabatan.setText("");
                
                TFNamaSekolah.setEditable(true);
                TFNamaSekolah.setEditable(true);
                TFNamaPerusahaan.setEditable(true);
                TFJabatan.setEditable(true);
            }
        });  
        
        

        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelPenyewaBaru = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        TFNamaPenyewa = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        CBStatusPenyewa = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        CBJenisKelamin = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        TFAlamat = new javax.swing.JTextField();
        PanelPekerja = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        TFNamaPerusahaan = new javax.swing.JTextField();
        TFJabatan = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        PanelPelajar = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        TFNamaSekolah = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        TFNamaJurusan = new javax.swing.JTextField();
        BTNinputPelajar = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        TFTglLahir = new javax.swing.JTextField();
        PanelMainMenu = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        BTNiNPUT = new javax.swing.JButton();
        BTNEditPenyewa = new javax.swing.JButton();
        PanelEditPenyewa = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        BTNHapus = new javax.swing.JButton();
        BTNUpdate = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        jLabel1.setText("KOS-KOSAN Ahmed");

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel2.setText("Nama Penyewa: ");

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel3.setText("Status Penyewa: ");

        CBStatusPenyewa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pekerja", "Pelajar", "Lainnya" }));
        CBStatusPenyewa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBStatusPenyewaActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel4.setText("Jenis Kelamin:");

        CBJenisKelamin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Laki-laki", "Perempuan", "Lainnya" }));
        CBJenisKelamin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBJenisKelaminActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel6.setText("alamat:");

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel5.setText("Nama Perusahaan:");

        TFNamaPerusahaan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFNamaPerusahaanActionPerformed(evt);
            }
        });

        TFJabatan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFJabatanActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel7.setText("Jabatan");

        javax.swing.GroupLayout PanelPekerjaLayout = new javax.swing.GroupLayout(PanelPekerja);
        PanelPekerja.setLayout(PanelPekerjaLayout);
        PanelPekerjaLayout.setHorizontalGroup(
            PanelPekerjaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPekerjaLayout.createSequentialGroup()
                .addGroup(PanelPekerjaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelPekerjaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TFNamaPerusahaan, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
                    .addComponent(TFJabatan)))
        );
        PanelPekerjaLayout.setVerticalGroup(
            PanelPekerjaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPekerjaLayout.createSequentialGroup()
                .addGroup(PanelPekerjaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(TFNamaPerusahaan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelPekerjaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(TFJabatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jLabel12.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel12.setText("Nama Sekolah/Kampus :");

        TFNamaSekolah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFNamaSekolahActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel13.setText("Jurusan:");

        TFNamaJurusan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFNamaJurusanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelPelajarLayout = new javax.swing.GroupLayout(PanelPelajar);
        PanelPelajar.setLayout(PanelPelajarLayout);
        PanelPelajarLayout.setHorizontalGroup(
            PanelPelajarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPelajarLayout.createSequentialGroup()
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(TFNamaJurusan, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelPelajarLayout.createSequentialGroup()
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TFNamaSekolah, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        PanelPelajarLayout.setVerticalGroup(
            PanelPelajarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPelajarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelPelajarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(TFNamaSekolah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelPelajarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(TFNamaJurusan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        BTNinputPelajar.setBackground(new java.awt.Color(102, 255, 102));
        BTNinputPelajar.setText("Input");
        BTNinputPelajar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNinputPelajarActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel10.setText("Tgl.Lahir: ");

        TFTglLahir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFTglLahirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelPenyewaBaruLayout = new javax.swing.GroupLayout(PanelPenyewaBaru);
        PanelPenyewaBaru.setLayout(PanelPenyewaBaruLayout);
        PanelPenyewaBaruLayout.setHorizontalGroup(
            PanelPenyewaBaruLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPenyewaBaruLayout.createSequentialGroup()
                .addGroup(PanelPenyewaBaruLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelPenyewaBaruLayout.createSequentialGroup()
                        .addContainerGap(138, Short.MAX_VALUE)
                        .addGroup(PanelPenyewaBaruLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(PanelPenyewaBaruLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(PanelPenyewaBaruLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(PanelPenyewaBaruLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(PanelPenyewaBaruLayout.createSequentialGroup()
                                            .addComponent(jLabel10)
                                            .addGap(363, 363, 363))
                                        .addComponent(PanelPekerja, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(PanelPenyewaBaruLayout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(102, 102, 102)
                                        .addGroup(PanelPenyewaBaruLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(TFAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(TFTglLahir, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(PanelPelajar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(28, 28, 28)
                                .addComponent(BTNinputPelajar))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PanelPenyewaBaruLayout.createSequentialGroup()
                                .addGroup(PanelPenyewaBaruLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PanelPenyewaBaruLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(PanelPenyewaBaruLayout.createSequentialGroup()
                                            .addComponent(jLabel2)
                                            .addGap(311, 311, 311))
                                        .addComponent(TFNamaPenyewa, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PanelPenyewaBaruLayout.createSequentialGroup()
                                        .addGroup(PanelPenyewaBaruLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel4))
                                        .addGroup(PanelPenyewaBaruLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(PanelPenyewaBaruLayout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addComponent(CBJenisKelamin, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(PanelPenyewaBaruLayout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addComponent(CBStatusPenyewa, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(PanelPenyewaBaruLayout.createSequentialGroup()
                        .addGap(173, 173, 173)
                        .addComponent(jLabel1)))
                .addContainerGap())
        );
        PanelPenyewaBaruLayout.setVerticalGroup(
            PanelPenyewaBaruLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPenyewaBaruLayout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68)
                .addGroup(PanelPenyewaBaruLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TFNamaPenyewa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelPenyewaBaruLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(CBStatusPenyewa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelPenyewaBaruLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(CBJenisKelamin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(PanelPenyewaBaruLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelPenyewaBaruLayout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(BTNinputPelajar))
                    .addGroup(PanelPenyewaBaruLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelPenyewaBaruLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TFAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelPenyewaBaruLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(TFTglLahir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PanelPekerja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PanelPelajar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/assets.png"))); // NOI18N

        BTNiNPUT.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        BTNiNPUT.setText("INPUT PENYEWA");
        BTNiNPUT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNiNPUTActionPerformed(evt);
            }
        });

        BTNEditPenyewa.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        BTNEditPenyewa.setText("Edit Penyewa ");
        BTNEditPenyewa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNEditPenyewaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelMainMenuLayout = new javax.swing.GroupLayout(PanelMainMenu);
        PanelMainMenu.setLayout(PanelMainMenuLayout);
        PanelMainMenuLayout.setHorizontalGroup(
            PanelMainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelMainMenuLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(PanelMainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BTNiNPUT, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelMainMenuLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(41, 41, 41))
                    .addComponent(BTNEditPenyewa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        PanelMainMenuLayout.setVerticalGroup(
            PanelMainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelMainMenuLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BTNiNPUT, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BTNEditPenyewa, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel8.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        jLabel8.setText("Edit Penyewa");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nama Penyewa", "Status Penyewa", "Jenis Kelamin", "alamat asal", "Tgl.Lahir", "Nama Perusahaan", "Jabatan", "Nama Sekolah/Kampus", "Jurusan"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        BTNHapus.setBackground(new java.awt.Color(255, 0, 0));
        BTNHapus.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BTNHapus.setText("Delete");
        BTNHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNHapusActionPerformed(evt);
            }
        });

        BTNUpdate.setBackground(new java.awt.Color(255, 255, 51));
        BTNUpdate.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BTNUpdate.setText("Update");
        BTNUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNUpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelEditPenyewaLayout = new javax.swing.GroupLayout(PanelEditPenyewa);
        PanelEditPenyewa.setLayout(PanelEditPenyewaLayout);
        PanelEditPenyewaLayout.setHorizontalGroup(
            PanelEditPenyewaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelEditPenyewaLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(PanelEditPenyewaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 831, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PanelEditPenyewaLayout.createSequentialGroup()
                        .addComponent(BTNHapus)
                        .addGap(18, 18, 18)
                        .addComponent(BTNUpdate)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelEditPenyewaLayout.createSequentialGroup()
                .addContainerGap(341, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(338, 338, 338))
        );
        PanelEditPenyewaLayout.setVerticalGroup(
            PanelEditPenyewaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelEditPenyewaLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(PanelEditPenyewaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTNHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTNUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(149, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(PanelMainMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(PanelEditPenyewa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelPenyewaBaru, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelMainMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(PanelEditPenyewa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(PanelPenyewaBaru, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CBStatusPenyewaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBStatusPenyewaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CBStatusPenyewaActionPerformed

    private void CBJenisKelaminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBJenisKelaminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CBJenisKelaminActionPerformed

    private void TFNamaPerusahaanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFNamaPerusahaanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFNamaPerusahaanActionPerformed

    private void TFJabatanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFJabatanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFJabatanActionPerformed

    private void BTNinputPelajarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNinputPelajarActionPerformed
        try {
            SimpleDateFormat dateS = new SimpleDateFormat("yyyy-MM-dd");
            String nama = TFNamaPenyewa.getText();
            String alamat = TFAlamat.getText();
            String Status = (String) CBStatusPenyewa.getSelectedItem();
            String JK = (String) CBJenisKelamin.getSelectedItem();
            String TglLahir = TFTglLahir.getText().trim();
            String NamaPerusahaan = TFNamaPerusahaan.getText();
            String Jabatan = TFJabatan.getText();
            String Kampus = TFNamaSekolah.getText();
            String Jurusan = TFNamaJurusan.getText();
            String id_penyewa = null;
            
            Connection kon = DataBase.getKoneksi();
            kon.setAutoCommit(false);
            
        java.util.Date utilDate = dateS.parse(TglLahir);
        
        // Convert to java.sql.Date for database
        java.sql.Date sqlDate = new java.sql.Date(utilDate.getTime());
            
            try {
                String sql1 = "INSERT INTO penyewa (nama, alamat, jenis_kelamin, tanggal_lahir, asal_kampus, jurusan, nama_perusahaan, jabatan) VALUES (?, ?, ?, ?, ?, ?, ?, ?)";
                PreparedStatement st1 = kon.prepareStatement(sql1, Statement.RETURN_GENERATED_KEYS); 
                st1.setString(1, nama);
                st1.setString(2, alamat);
                st1.setString(3, JK);
                st1.setDate(4, sqlDate);
                st1.setString(5, Kampus);
                st1.setString(6, Jurusan);
                st1.setString(7, NamaPerusahaan);
                st1.setString(8, Jabatan);
                st1.executeUpdate();
                if (id_penyewa == null){
                ResultSet rs = st1.getGeneratedKeys();
                if(rs.next()){
                int generatedId = rs.getInt(1);
                kon.commit();
                }
                }
                
            } catch (SQLException e) {
            // Rollback if any error occurs
            kon.rollback();
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        } finally {
            // Reset auto-commit and close connection
            kon.setAutoCommit(true);
            kon.close();
}
            
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            model.addRow(new Object[]{nama, Status, JK, alamat, TglLahir, NamaPerusahaan, Jabatan, Kampus, Jurusan});
            
            TFNamaPenyewa.setText("");
            TFAlamat.setText("");
            CBStatusPenyewa.setSelectedItem("Pekerja");
            CBJenisKelamin.setSelectedItem("Laki-laki");
            TFTglLahir.setText("");
            TFNamaPerusahaan.setText("");
            TFJabatan.setText("");
            TFNamaSekolah.setText("");
            TFNamaJurusan.setText("");
        } catch (SQLException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParseException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BTNinputPelajarActionPerformed

    private void BTNiNPUTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNiNPUTActionPerformed
        PanelMainMenu.setVisible(true);
        PanelPenyewaBaru.setVisible(true);
        PanelPekerja.setVisible(true);
        PanelEditPenyewa.setVisible(false);
    }//GEN-LAST:event_BTNiNPUTActionPerformed

    private void BTNEditPenyewaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNEditPenyewaActionPerformed
        PanelMainMenu.setVisible(true);
        PanelPenyewaBaru.setVisible(false);
        PanelEditPenyewa.setVisible(true);
    }//GEN-LAST:event_BTNEditPenyewaActionPerformed

    private void TFNamaSekolahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFNamaSekolahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFNamaSekolahActionPerformed

    private void TFNamaJurusanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFNamaJurusanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFNamaJurusanActionPerformed

    private void TFTglLahirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFTglLahirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFTglLahirActionPerformed


    private void BTNUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNUpdateActionPerformed
        int row = jTable1.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(null, "Pilih baris terlebih dahulu!");
            return;
        }

        String id = jTable1.getValueAt(row, 0).toString();
        String nama = jTable1.getValueAt(row, 1).toString();
        String alamat = jTable1.getValueAt(row, 2).toString();
        String kelamin = jTable1.getValueAt(row, 3).toString();
        String tglLahir = jTable1.getValueAt(row, 4).toString();
        String jurusan = jTable1.getValueAt(row, 5).toString();
        String asalKampus = jTable1.getValueAt(row, 6).toString();
        String jabatan = jTable1.getValueAt(row, 7).toString();
        String perusahaan = jTable1.getValueAt(row, 8).toString();


        DialogUpdate dialog = new DialogUpdate(id, nama, alamat, kelamin, tglLahir, jurusan, asalKampus, jabatan, perusahaan);
        dialog.setVisible(true);

      
        loadTable();
    }//GEN-LAST:event_BTNUpdateActionPerformed
private void hapusDataPenyewa() {
    int selectedRow = jTable1.getSelectedRow();

    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(null, "Pilih baris data yang ingin dihapus terlebih dahulu.");
    } else {
        int konfirmasi = JOptionPane.showConfirmDialog(null,
            "Yakin ingin menghapus data ini?",
            "Konfirmasi Hapus",
            JOptionPane.YES_NO_OPTION);

        if (konfirmasi == JOptionPane.YES_OPTION) {
            try {
                // Ambil ID dari kolom pertama (kolom ID)
                int idPenyewa = (int) jTable1.getValueAt(selectedRow, 0);

                // Hapus dari database
                Connection conn = DataBase.getKoneksi();
                String sql = "DELETE FROM Penyewa WHERE id_penyewa = ?";
                PreparedStatement ps = conn.prepareStatement(sql);
                ps.setInt(1, idPenyewa);
                int affectedRows = ps.executeUpdate();

                if (affectedRows > 0) {
                    JOptionPane.showMessageDialog(null, "Data berhasil dihapus dari database.");
                    tampilkanDataPenyewa(); // Refresh tabel
                } else {
                    JOptionPane.showMessageDialog(null, "Data gagal dihapus dari database.");
                }

                ps.close();
                conn.close();

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Terjadi kesalahan saat menghapus data: " + e.getMessage());
            }
        }
    }
}
    private void BTNHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNHapusActionPerformed
        hapusDataPenyewa();
    }//GEN-LAST:event_BTNHapusActionPerformed
private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        Vector<Vector> TableData = model.getDataVector();
        
        try {
        FileOutputStream file = new FileOutputStream("file.bin");
        ObjectOutputStream output =  new ObjectOutputStream(file);
        
        output.writeObject(TableData);
        
        output.close();
        file.close();
        }catch (Exception ex){
        ex.printStackTrace();
        }
    }//GEN-LAST:event_formWindowClosing

    private void formWindowOpened(java.awt.event.WindowEvent evt) {                                  
        try {
        FileInputStream file = new FileInputStream("file.bin");
        ObjectInputStream input =  new ObjectInputStream(file);
        
         Vector<Vector> TableData =  (Vector<Vector>)input.readObject();
        
        input.close();
        file.close();
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        for(int i = 0; i< TableData.size(); i++){
        Vector row = TableData.get(i);
        model.addRow(new Object[]{row.get(0),row.get(1),row.get(2),row.get(3)});
        }
        }catch (Exception ex){
        ex.printStackTrace();
        }
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
            
        });
        
    }
private void tampilkanDataPenyewa() {
    DefaultTableModel model = new DefaultTableModel();
    model.addColumn("ID");
    model.addColumn("Nama");
    model.addColumn("Alamat");
    model.addColumn("Jenis Kelamin");
    model.addColumn("Tanggal Lahir");
    model.addColumn("Jurusan");
    model.addColumn("Asal Kampus");
    model.addColumn("Jabatan");
    model.addColumn("Nama Perusahaan");

    try {
        Connection conn = DataBase.getKoneksi();
        Statement stmt = conn.createStatement();
        ResultSet rs = stmt.executeQuery("SELECT * FROM Penyewa");

        while (rs.next()) {
            model.addRow(new Object[]{
                rs.getInt("id_penyewa"),
                rs.getString("nama"),
                rs.getString("alamat"),
                rs.getString("jenis_kelamin"),
                rs.getDate("tanggal_lahir"),
                rs.getString("jurusan"),
                rs.getString("asal_kampus"),
                rs.getString("jabatan"),
                rs.getString("nama_perusahaan")
            });
        }

        jTable1.setModel(model);
      

        stmt.close();
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Gagal menampilkan data: " + e.getMessage());
    }
}
public void loadTable() {
    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
model.setRowCount(0); // Clear data lama

try {
    Connection conn = DataBase.getKoneksi();
    Statement st = conn.createStatement();
    ResultSet rs = st.executeQuery("SELECT * FROM penyewa");

    while (rs.next()) {
        model.addRow(new Object[]{
            rs.getInt("id_penyewa"),
            rs.getString("nama"),
            rs.getString("alamat"),
            rs.getString("jenis_kelamin"),
            rs.getString("tanggal_lahir"),
            rs.getString("jurusan"),
            rs.getString("asal_kampus"),
            rs.getString("jabatan"),
            rs.getString("nama_perusahaan")
        });
    }
} catch (Exception e) {
    e.printStackTrace();
}
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNEditPenyewa;
    private javax.swing.JButton BTNHapus;
    private javax.swing.JButton BTNUpdate;
    private javax.swing.JButton BTNiNPUT;
    private javax.swing.JButton BTNinputPelajar;
    private javax.swing.JComboBox<String> CBJenisKelamin;
    private javax.swing.JComboBox<String> CBStatusPenyewa;
    private javax.swing.JPanel PanelEditPenyewa;
    private javax.swing.JPanel PanelMainMenu;
    private javax.swing.JPanel PanelPekerja;
    private javax.swing.JPanel PanelPelajar;
    private javax.swing.JPanel PanelPenyewaBaru;
    private javax.swing.JTextField TFAlamat;
    private javax.swing.JTextField TFJabatan;
    private javax.swing.JTextField TFNamaJurusan;
    private javax.swing.JTextField TFNamaPenyewa;
    private javax.swing.JTextField TFNamaPerusahaan;
    private javax.swing.JTextField TFNamaSekolah;
    private javax.swing.JTextField TFTglLahir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}

